# Generated by Django 5.0.4 on 2024-04-20 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ['-created_on']},
        ),
    ]
