# Generated by Django 5.0.4 on 2024-04-21 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='wodtitle',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='workoutcomment',
            old_name='wodtitle',
            new_name='title',
        ),
    ]
