# Generated by Django 5.0.4 on 2024-04-21 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_rename_wodtitle_workout_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutcomment',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_comments', to='workout.workout'),
        ),
    ]
