# Generated by Django 5.0.4 on 2024-04-21 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_alter_workoutcomment_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutcomment',
            old_name='title',
            new_name='post',
        ),
    ]
