# Generated by Django 5.0.4 on 2024-04-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_header_about_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='header',
            old_name='updated_on',
            new_name='created_on',
        ),
        migrations.AddField(
            model_name='about',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
