# Generated by Django 5.0.4 on 2024-04-16 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_rename_updated_on_header_created_on_about_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ['-updated_on']},
        ),
    ]
